// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/info': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/info').default>>>>
    }
    '/api/todo': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todo').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.14.159_@parcel+watcher@2.5.0_@types+node@22.9.0_eslint@9.15.0_jiti@2.4.0__ioredis@5.4._2v4bcuzmxiif7hsbxug4cj4fwu/node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}