apiVersion: apps/v1
kind: Deployment
metadata:
  name: sif-viz-component
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sif-viz-component
  template:
    metadata:
      labels:
        app: sif-viz-component
    spec:
      containers:
        - name: sif-viz-component
          image: marsprezentace/sif-viz-component:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: sif-viz-component-configmap
