apiVersion: v1
kind: Service
metadata:
  name: <component-name>
spec:
  type: NodePort
  ports:
    - name: <component-name>
      port: 9000
      targetPort: 9000
      nodePort: 9000
      protocol: TCP
  selector:
    app: <component-name>
