apiVersion: v1
kind: Service
metadata:
  name: sif-viz-component
spec:
  type: NodePort
  ports:
    - name: sif-viz-component
      port: 9000
      targetPort: 9000
      nodePort: 9000
      protocol: TCP
  selector:
    app: sif-viz-component
