apiVersion: v1
kind: Service
metadata:
  name: homecare-hub
spec:
  type: NodePort
  ports:
    - name: homecare-hub
      port: 3000
      targetPort: 3000
      nodePort: 30031
      protocol: TCP
  selector:
    app: homecare-hub
